### ISSUE TITLE
Добавить ссылку/форму авторизации

### ISSUE THREAD

**Issue by tipsun91** [Gemorroj/forum#25]
Добавить ссылку/форму авторизации

**Comment by Gemorroj** [comment]
нужно убрать любой текст из кнопки, оставить только иконку (как на вапинете). иначе на небольших разрешениях текст заголовка страницы налазит на кнопку справа.
![-1](https://cloud.githubusercontent.com/assets/885731/14224933/8499fc16-f8b7-11e5-8535-1e1875b0440d.png)

**Comment by Gemorroj** [comment]
ник тоже убрать надо
